### PR TITLE
Bring back support for Ruby 2.1

### PR DESCRIPTION
**Pull request by bquorning**
Following the discussion in https://github.com/backus/rubocop-rspec/pull/131 where several (more than one) people expressed their wanting to use the newest version of rubocop-rspec with Ruby 2.1.

cc @backus

### CODE REVIEW

**Comment by backus** [comment]
Thanks. I'll have to push your commit since right now it halts the build if people other than me change the build steps for security reasons.

**Comment by backus** [comment]
@bquorning thanks. I'll finish up this branch since I have to add 2.1 to the dockerfile :smile:

**Comment by bquorning** [comment]
Sounds good. You’ll rebase as well? Those `#fetch`/`#[]` specs we fixed in #214 are still failing here.

**Comment by backus** [comment]
Yup I'll rebase as well

**Comment by backus** [comment]
Looks like I'll have to fix one issue with building the native json gem in ruby 2.1. I'll look into it soon

**Comment by backus** [comment]
Thanks @bquorning

**Pull request merged**
