### PR TITLE
Disable MessageExpectation cop

### PR DESCRIPTION
**Pull request by bquorning**
Users have expressed confusion over this cop; see

 - https://github.com/backus/rubocop-rspec/issues/23
 - https://github.com/backus/rubocop-rspec/pull/169
 - https://github.com/backus/rubocop-rspec/issues/218
 - https://github.com/backus/rubocop-rspec/pull/224
 - https://github.com/backus/rubocop-rspec/issues/229

### CODE REVIEW

**Comment by bquorning** [comment]
@backus Where do we put the configuration for disabled cops?

**Comment by backus** [comment]
@bquorning. Lets just toss it in the default.yml for now. I don't think we need to maintain two files yet

**Comment by backus** [comment]
@bquorning once this is merged can you do a minor version bump and release to rubygems?

**Comment by bquorning** [comment]
What I meant was: how do I get a green build? ;-)

**Comment by backus** [comment]
oh haha. I guess we need to update that test.

**Comment by backus** [comment]
@bquorning the failing test can be updated to:

```ruby
it 'includes Enabled: true for every cop' do
  expect(cop_configuration('Enabled')).to all(be(true).or(be(false)))
end
```

Basically we are asserting that it is present and a boolean

**Comment by bquorning** [comment]
@backus Was that a +1?

**Comment by backus** [comment]
Yeah sorry I was on my phone.

**Pull request merged**
