### PR TITLE
Remove unused lets

### PR DESCRIPTION
**Pull request by dgollahon**

### CODE REVIEW

**Comment by backus** [comment]
How meta. Thanks for improving the specs 😆

**Comment by bquorning** [comment]
👍 , but I’m still sad that #201 wasn’t possible.

**Comment by dgollahon** [comment]
> 👍 , but I’m still sad that #201 wasn’t possible.

Yeah. I'm hoping to pick up @backus's separate tool effort when I get some free time. We'll see.

**Comment by backus** [comment]
@bquorning you can try it out it is just kinda flimsy. http://github.com/backus/rspec-lint

Just run it like `bundle exec rspec-lint spec/`

It may blow up heh

**Comment by dgollahon** [comment]
> > 👍 , but I’m still sad that #201 wasn’t possible.
>Yeah. I'm hoping to pick up @backus's separate tool effort when I get some free time. We'll see.

@bquorning: btw, i did finally put some effort into this. it definitely has room to improve, but works well enough to release an 0.0.1: [rspectre](https://github.com/dgollahon/rspectre)

**Pull request merged**
