### PR TITLE
Add it_has_behavior to Includes::ALL

### PR DESCRIPTION
**Pull request by jdelStrother**

### CODE REVIEW

**Comment by backus** [comment]
@jdelStrother I don't think this is a builtin include

**Comment by jdelStrother** [comment]
Yeah, sorry - you're right.   I think I confused myself 😕

**Comment by backus** [comment]
No problem! Was there a particular use case you were trying to fix? This made me think about whether we should add a configuration option for globally specifying example group aliases.

**Comment by jdelStrother** [comment]
It looks like someone added the alias from https://www.relishapp.com/rspec/rspec-core/v/2-0/docs/example-groups/shared-example-group#aliasing-"it-should-behave-like"-to-"it-has-behavior" to our project config because it read better in some cases. I didn't realise it wasn't built in - I might try and reword things back to the default methods.

**Comment by backus** [comment]
Cool. In the meantime that will give you better static analysis via rubocop-rspec. The `RSpec/EmptyExampleGroup` cop has the `CustomIncludeMethods` but realistically this should be a global config!

**Pull request closed without merging**
