### PR TITLE
Count aggregate_failures block as single expectation

### PR DESCRIPTION
**Pull request by Darhazer**
Basic implementation of #233

Let me know if you want me to implement some of the options suggested in the #233

### CODE REVIEW

**Comment by backus** [comment]
Is it possible to instead redefine the `expect` matcher to `(send _ {:expect :aggregate_failures} ...)`?

**Comment by backus** [comment]
It isn't as simple as modifying the node pattern, but how do you feel about instead altering the behavior of the recursive example search to stop at `aggregate_failures` too? Then we don't have to count and then search again to decrement nodes within `aggregate_failures`?

**Comment by Darhazer** [comment]
Re-implemented. Not sure if this is what you meant though

**Comment by backus** [comment]
Looks great! Thanks @Darhazer

**Comment by backus** [comment]
@Darhazer I really appreciate your recent contributions. Would you be interested in joining as a collaborator? You'd be able to push to the repo directly, I'd ping you for reviews occasionally, and you could help with things like cutting releases.

**Comment by Darhazer** [comment]
@backus I'd be honored

**Comment by backus** [comment]
@Darhazer invited! Thanks for helping out and I'm excited to what you PR next :smile:

**Pull request merged**
