### PR TITLE
Rename ExpectViolation to ExpectOffense

### PR DESCRIPTION
**Pull request by backus**
I'd like to upstream this to RuboCop soon!

 - Drops dependency on concord
 - Drops dependency on anima
 - Drops dependency on adamantium

See also bbatsov/rubocop#3905

### CODE REVIEW

**Comment by backus** [comment]
@dgollahon WDYT? I'd be open to a PR that makes the classes a bit bigger if you are interested but I personally don't want to do that right now 😆.

**Comment by dgollahon** [comment]
> @dgollahon WDYT?

I think the renaming makes sense. Why'd you decide to remove the dev dependencies? Was it for moving to `rubocop`? Because otherwise I think having lightweight dev dependencies is pretty harmless.

> I'd be open to a PR that makes the classes a bit bigger if you are interested

WDYM?

If you're talking about general changes to this, I think one of the biggest things to do would be to make error messages more reasonable (maybe using some rspec features would be helpful?). It can be a bit frustrating to debug some cases.

**Comment by backus** [comment]
@dgollahon yeah I'm trying to eventually upstream this to RuboCop. See bbatsov/rubocop#3905. That is the reason for the rename and the dev dependency removal.

> > I'd be open to a PR that makes the classes a bit bigger if you are interested
> WDYM?

> If you're talking about general changes to this, I think one of the biggest things to do would be to make error messages more reasonable (maybe using some rspec features would be helpful?). It can be a bit frustrating to debug some cases.

Well I figured that you'd probably agree this has "tiny class syndrome." Was just preempting discussion about reducing that

**Comment by dgollahon** [comment]
> Well I figured that you'd probably agree this has "tiny class syndrome." Was just preempting discussion about reducing that

Ah, yeah. Since this wasn't new code or a directed refactor I didn't really think nitpicking the implementation was terribly important. The object could probably be improved but that doesn't have to be done right now.

**Pull request merged**
