### PR TITLE
Add DescribeSymbol cop

### PR DESCRIPTION
**Pull request by tsigo**
This cop will add offenses when a Symbol is used as the first argument
to `describe`.

Describing a Symbol changes the behavior of `described_class` in an
unexpected way. See https://github.com/rspec/rspec-core/issues/1610 and
http://docs.gitlab.com/ce/development/gotchas.html#dont-describe-symbols

### CODE REVIEW

**Comment by tsigo** [comment]
Not sure why CI didn't run for this one.

**Comment by tsigo** [comment]
@nevir Force pushed to trigger a CI run. Failures look to be unrelated.

**Comment by tjwp** [comment]
I think the test failure is because json 2.0 requires ruby 2.0 or later. I included a fix for that here: https://github.com/nevir/rubocop-rspec/pull/109/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R6

RuboCop had to make a similar change recently to keep tests passing with 1.9.

**Comment by dgollahon** [comment]
@tsigo: I'm going to close this PR since it seems to have gone stale. I'm willing to pick this up on your behalf when I get some free time, or you're welcome to resume it if you prefer--just let me know if you want to work on it. :)

In either case, I'd like to see the implementation updated to use our current node matching patterns and convert the specs to using the `expect_violation` syntax we favor now.

**Comment by tsigo** [comment]
@dgollahon I've got an update ready to go to match the current style -- please re-open this one. ❤️

**Comment by dgollahon** [comment]
@tsigo: Great. :)

I think you actually have to do the reopen for some reason--the button is greyed out on my end. Sometimes github is a little weird when you force push / override older branches. If, for some reason, it won't let you reopen it either, try pushing again or feel free to open a separate PR to pick up where you left off here.

**Comment by tsigo** [comment]
@dgollahon No option on my end either; I'll open a new one. 👍

**Pull request closed without merging**
