### PR TITLE
Add AroundBlock cop. Fixes #315

### LINKED ISSUE #315: Detect invalid `around`
```
# bad
around do
  blah
end

# bad
around do |test|
  blah
end

# good
around do |test|
  blah
  test.call
end

# good
around do |test|
  blah
  test.run
end

# ignore this since it is hard to know statically
around do |test|
  blah
  method_invocation(&test)
end
```

### PR DESCRIPTION
**Pull request by Darhazer**
@backus 
Unfortunately I didn't find an easy way to avoid the instance var in this cop as well.
Please review the error messages.

### CODE REVIEW

**Comment by backus** [comment]
@Darhazer What about just defining a node matcher for `around` blocks? In the cases where it yields an lvar we could just do a search and avoid using the variable force which I find sort of complicated (definitely worth it for RuboCop but I personally haven't implemented anything with it). Thoughts?

**Comment by Darhazer** [comment]
I'll attempt this re-implementation over the weekend :+1: 
Btw I tried this initially (as the hooks argument uses it) but then realized that I don't know how to check block arguments and switched to VariableForce instead. But with a node matcher it will look simpler, so I'll give another try.

**Comment by backus** [comment]
@Darhazer Great. Also make sure to look into `def_node_search`. Works exactly the same way but makes it really easy to just recursively search starting at a given node

**Comment by Darhazer** [comment]
PR updated

**Comment by backus** [comment]
Looking good! You have some style violations but after that I think I'm good to merge

**Comment by Darhazer** [comment]
PR updated

**Comment by backus** [comment]
@Darhazer almost there! We have a build step which asserts that the documented description is the same as the one in the config. Can you update them so they are the same? You can just run `bin/build_config` and commit the result

**Comment by Darhazer** [comment]
Fixed. Any idea why it doesn't fail when running `rspec`? How can I test the entire build locally?

**Comment by backus** [comment]
I just don't have it implemented with RSpec. If you run `bundle exec rake` it should be identical to CI

**Pull request merged**
