### PR TITLE
Use Circle CI instead of Travis

### PR DESCRIPTION
**Pull request by bquorning**
For a while now I’ve been wanting to switch from Travis CI to Circle CI. In my experience, Circle is much, much faster than Travis, and seeing how we suddenly get weird errors when trying out a new Ruby (#526), I’m leaning even more towards Circle.

There are a few TODOs though:

- [x] Set up Circle CI (https://circleci.com/signup/ -> Sign up with GitHub -> Public Repos Only) for backus/rubocop-rspec
- [ ] ~Remove Travis config~
- [ ] ~Disconnect Travis?~
- [ ] ~Change Travis “status image” in the Readme to a Circle equivalent.~
- [ ] ~Fix codeclimate integration.~

The last 4 items, we’ll do later.

### CODE REVIEW

**Comment by backus** [comment]
High level, I'm all for dropping Travis for Circle. When I setup the buildkite I thought they would have public build pages by now but I guess they're still working on that. I just clicked through the repo setup for circle for this project so you should be able to edit the config and whatnot now

**Comment by backus** [comment]
Looks great! I played with the new circle CI config a bit recently for a private project and I really like their new setup. It seems like a more managed version of what I tried to setup for BK.

**Comment by bquorning** [comment]
Should this PR include removal of Travis and Buildkite code? Or should that be in a follow-up PR?

I guess both services would need to be “detached” from this repository in order to not continue testing all PRs, right?

**Comment by bquorning** [comment]
So… I’m reducing the scope of this PR to:

- [x] Set up Circle CI.

In other pull requests we’ll discuss:

- Integrate CircleCI with CodeClimate.
- Disconnect Travis and remove config, and fix CI status image in Readme.
- Disconnect BuildKite and remove config.

which means this PR is done.

**Comment by Tr4pSt3R** [comment]
@bquorning are these PRs ready or should they be added as issues and labelled as improvements so that they are, somehow, accountable?
Re:
```
In other pull requests we’ll discuss:

Integrate CircleCI with CodeClimate.
Disconnect Travis and remove config, and fix CI status image in Readme.
Disconnect BuildKite and remove config.
```

**Comment by bquorning** [comment]
@Tr4pSt3R I’ll probably just open those PRs one by one after merging this one.

**Pull request merged**
